// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Votify.Infrastructure;

#nullable disable

namespace Votify.Infrastructure.Migrations
{
    [DbContext(typeof(VotifyDbContext))]
    [Migration("20260304153412_AddUsuariosHierarchy")]
    partial class AddUsuariosHierarchy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Votify.Domain.UserFolder.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Votify.Domain.VoteFoler.Vote", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VoteType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("VotedProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Votes");

                    b.HasDiscriminator<string>("VoteType").HasValue("Vote");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Votify.Domain.UserFolder.Jury", b =>
                {
                    b.HasBaseType("Votify.Domain.UserFolder.User");

                    b.HasDiscriminator().HasValue("Jurado");
                });

            modelBuilder.Entity("Votify.Domain.UserFolder.Organizer", b =>
                {
                    b.HasBaseType("Votify.Domain.UserFolder.User");

                    b.HasDiscriminator().HasValue("Organizador");
                });

            modelBuilder.Entity("Votify.Domain.UserFolder.Participant", b =>
                {
                    b.HasBaseType("Votify.Domain.UserFolder.User");

                    b.HasDiscriminator().HasValue("Participante");
                });

            modelBuilder.Entity("Votify.Domain.UserFolder.Public", b =>
                {
                    b.HasBaseType("Votify.Domain.UserFolder.User");

                    b.HasDiscriminator().HasValue("PublicoGeneral");
                });

            modelBuilder.Entity("Votify.Domain.VoteFoler.ExpertVote", b =>
                {
                    b.HasBaseType("Votify.Domain.VoteFoler.Vote");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Expert");
                });

            modelBuilder.Entity("Votify.Domain.VoteFoler.PublicVote", b =>
                {
                    b.HasBaseType("Votify.Domain.VoteFoler.Vote");

                    b.HasDiscriminator().HasValue("Public");
                });
#pragma warning restore 612, 618
        }
    }
}
