// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Votify.Infrastructure;

#nullable disable

namespace Votify.Infrastructure.Migrations
{
    [DbContext(typeof(VotifyDbContext))]
    [Migration("20260424155150_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Votify.Domain.AuditFolder.AuditRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("AuditRequests");
                });

            modelBuilder.Entity("Votify.Domain.CategoryFolder.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("AllowSelfVoting")
                        .HasColumnType("boolean");

                    b.Property<bool>("CombineResults")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("JuryWeight")
                        .HasPrecision(5, 4)
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("PublicWeight")
                        .HasPrecision(5, 4)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Votify.Domain.CategoryFolder.Criterion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VotingSessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Weight")
                        .HasPrecision(5, 4)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("VotingSessionId");

                    b.ToTable("Criteria");
                });

            modelBuilder.Entity("Votify.Domain.CategoryFolder.Prize", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetVoter")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Prizes");
                });

            modelBuilder.Entity("Votify.Domain.EventFolder.Event", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("MaxProjects")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasDiscriminator<string>("EventType").HasValue("Event");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Votify.Domain.ProjectFolder.CriterionScore", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("CriterionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectCategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CriterionId");

                    b.HasIndex("ProjectCategoryId");

                    b.ToTable("CriterionScores");
                });

            modelBuilder.Entity("Votify.Domain.ProjectFolder.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasDiscriminator<string>("ProjectType").HasValue("Project");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Votify.Domain.ProjectFolder.ProjectCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .HasColumnType("text");

                    b.Property<int?>("FinalRank")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRankManual")
                        .HasColumnType("boolean");

                    b.Property<string>("ProjectId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProjectId", "CategoryId")
                        .IsUnique();

                    b.ToTable("ProjectCategories");
                });

            modelBuilder.Entity("Votify.Domain.ProjectFolder.ProjectMaterial", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectMaterial");
                });

            modelBuilder.Entity("Votify.Domain.UserFolder.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Votify.Domain.VoteFolder.Vote", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IntegrityHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TopPosition")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VoteType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("VotedProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VotingSessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VotingSessionId");

                    b.ToTable("Votes");

                    b.HasDiscriminator<string>("VoteType").HasValue("Vote");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Votify.Domain.VoteFolder.VotingSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AdjustedCloseAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("AllowComments")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowCommentsPerCriterion")
                        .HasColumnType("boolean");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CloseAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CriterionType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EvaluationType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsManuallyAdjusted")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxPointsPerProject")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OpenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PointsPerVoter")
                        .HasColumnType("integer");

                    b.Property<int?>("ReminderMinutesBeforeClose")
                        .HasColumnType("integer");

                    b.Property<bool>("RequireComments")
                        .HasColumnType("boolean");

                    b.Property<int?>("TopN")
                        .HasColumnType("integer");

                    b.Property<int>("VoterType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("VotingSessions");
                });

            modelBuilder.Entity("Votify.Domain.EventFolder.ModalityEvent", b =>
                {
                    b.HasBaseType("Votify.Domain.EventFolder.Event");

                    b.Property<string>("modality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Modality");
                });

            modelBuilder.Entity("Votify.Domain.ProjectFolder.AiProject", b =>
                {
                    b.HasBaseType("Votify.Domain.ProjectFolder.Project");

                    b.HasDiscriminator().HasValue("AI");
                });

            modelBuilder.Entity("Votify.Domain.ProjectFolder.GeneralProject", b =>
                {
                    b.HasBaseType("Votify.Domain.ProjectFolder.Project");

                    b.HasDiscriminator().HasValue("General");
                });

            modelBuilder.Entity("Votify.Domain.ProjectFolder.SustainabilityProject", b =>
                {
                    b.HasBaseType("Votify.Domain.ProjectFolder.Project");

                    b.HasDiscriminator().HasValue("Sustainability");
                });

            modelBuilder.Entity("Votify.Domain.UserFolder.Organizer", b =>
                {
                    b.HasBaseType("Votify.Domain.UserFolder.User");

                    b.HasDiscriminator().HasValue("Organizador");
                });

            modelBuilder.Entity("Votify.Domain.UserFolder.Voter", b =>
                {
                    b.HasBaseType("Votify.Domain.UserFolder.User");

                    b.HasDiscriminator().HasValue("Voter");
                });

            modelBuilder.Entity("Votify.Domain.VoteFolder.ExpertVote", b =>
                {
                    b.HasBaseType("Votify.Domain.VoteFolder.Vote");

                    b.HasDiscriminator().HasValue("Expert");
                });

            modelBuilder.Entity("Votify.Domain.VoteFolder.PublicVote", b =>
                {
                    b.HasBaseType("Votify.Domain.VoteFolder.Vote");

                    b.HasDiscriminator().HasValue("Public");
                });

            modelBuilder.Entity("Votify.Domain.UserFolder.Jury", b =>
                {
                    b.HasBaseType("Votify.Domain.UserFolder.Voter");

                    b.HasDiscriminator().HasValue("Jurado");
                });

            modelBuilder.Entity("Votify.Domain.UserFolder.Participant", b =>
                {
                    b.HasBaseType("Votify.Domain.UserFolder.Voter");

                    b.HasDiscriminator().HasValue("Participante");
                });

            modelBuilder.Entity("Votify.Domain.UserFolder.Public", b =>
                {
                    b.HasBaseType("Votify.Domain.UserFolder.Voter");

                    b.HasDiscriminator().HasValue("PublicoGeneral");
                });

            modelBuilder.Entity("Votify.Domain.CategoryFolder.Category", b =>
                {
                    b.HasOne("Votify.Domain.EventFolder.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Votify.Domain.CategoryFolder.Criterion", b =>
                {
                    b.HasOne("Votify.Domain.VoteFolder.VotingSession", "VotingSession")
                        .WithMany("Criteria")
                        .HasForeignKey("VotingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VotingSession");
                });

            modelBuilder.Entity("Votify.Domain.CategoryFolder.Prize", b =>
                {
                    b.HasOne("Votify.Domain.CategoryFolder.Category", "Category")
                        .WithMany("Prizes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Votify.Domain.ProjectFolder.CriterionScore", b =>
                {
                    b.HasOne("Votify.Domain.CategoryFolder.Criterion", "Criterion")
                        .WithMany()
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Votify.Domain.ProjectFolder.ProjectCategory", "ProjectCategory")
                        .WithMany("CriterionScores")
                        .HasForeignKey("ProjectCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterion");

                    b.Navigation("ProjectCategory");
                });

            modelBuilder.Entity("Votify.Domain.ProjectFolder.ProjectCategory", b =>
                {
                    b.HasOne("Votify.Domain.CategoryFolder.Category", "Category")
                        .WithMany("ProjectCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Votify.Domain.ProjectFolder.Project", "Project")
                        .WithMany("ProjectCategories")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Votify.Domain.ProjectFolder.ProjectMaterial", b =>
                {
                    b.HasOne("Votify.Domain.ProjectFolder.Project", null)
                        .WithMany("Materials")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Votify.Domain.VoteFolder.Vote", b =>
                {
                    b.HasOne("Votify.Domain.VoteFolder.VotingSession", "VotingSession")
                        .WithMany("Votes")
                        .HasForeignKey("VotingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VotingSession");
                });

            modelBuilder.Entity("Votify.Domain.VoteFolder.VotingSession", b =>
                {
                    b.HasOne("Votify.Domain.CategoryFolder.Category", "Category")
                        .WithMany("VotingSessions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Votify.Domain.CategoryFolder.Category", b =>
                {
                    b.Navigation("Prizes");

                    b.Navigation("ProjectCategories");

                    b.Navigation("VotingSessions");
                });

            modelBuilder.Entity("Votify.Domain.ProjectFolder.Project", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("ProjectCategories");
                });

            modelBuilder.Entity("Votify.Domain.ProjectFolder.ProjectCategory", b =>
                {
                    b.Navigation("CriterionScores");
                });

            modelBuilder.Entity("Votify.Domain.VoteFolder.VotingSession", b =>
                {
                    b.Navigation("Criteria");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
