// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Votify.Infrastructure;

#nullable disable

namespace Votify.Infrastructure.Migrations
{
    [DbContext(typeof(VotifyDbContext))]
    [Migration("20260306110509_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Votify.Domain.CategoryFolder.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrizeDescription")
                        .HasColumnType("text");

                    b.Property<double>("WeightCriterionA")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<double>("WeightCriterionB")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Votify.Domain.EventFolder.Event", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxProjects")
                        .HasColumnType("integer");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Votify.Domain.ProjectFolder.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CriterionA")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<double>("CriterionB")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Projects");

                    b.HasDiscriminator<string>("ProjectType").HasValue("Project");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Votify.Domain.UserFolder.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Votify.Domain.VoteFolder.Vote", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("RawScore")
                        .HasColumnType("double precision");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VoteType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("VotedProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Votes");

                    b.HasDiscriminator<string>("VoteType").HasValue("Vote");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Votify.Domain.ProjectFolder.AiProject", b =>
                {
                    b.HasBaseType("Votify.Domain.ProjectFolder.Project");

                    b.HasDiscriminator().HasValue("AI");
                });

            modelBuilder.Entity("Votify.Domain.ProjectFolder.SustainabilityProject", b =>
                {
                    b.HasBaseType("Votify.Domain.ProjectFolder.Project");

                    b.HasDiscriminator().HasValue("Sustainability");
                });

            modelBuilder.Entity("Votify.Domain.UserFolder.Jury", b =>
                {
                    b.HasBaseType("Votify.Domain.UserFolder.User");

                    b.HasDiscriminator().HasValue("Jurado");
                });

            modelBuilder.Entity("Votify.Domain.UserFolder.Organizer", b =>
                {
                    b.HasBaseType("Votify.Domain.UserFolder.User");

                    b.HasDiscriminator().HasValue("Organizador");
                });

            modelBuilder.Entity("Votify.Domain.UserFolder.Participant", b =>
                {
                    b.HasBaseType("Votify.Domain.UserFolder.User");

                    b.HasDiscriminator().HasValue("Participante");
                });

            modelBuilder.Entity("Votify.Domain.UserFolder.Public", b =>
                {
                    b.HasBaseType("Votify.Domain.UserFolder.User");

                    b.HasDiscriminator().HasValue("PublicoGeneral");
                });

            modelBuilder.Entity("Votify.Domain.VoteFolder.ExpertVote", b =>
                {
                    b.HasBaseType("Votify.Domain.VoteFolder.Vote");

                    b.HasDiscriminator().HasValue("Expert");
                });

            modelBuilder.Entity("Votify.Domain.VoteFolder.PublicVote", b =>
                {
                    b.HasBaseType("Votify.Domain.VoteFolder.Vote");

                    b.HasDiscriminator().HasValue("Public");
                });

            modelBuilder.Entity("Votify.Domain.CategoryFolder.Category", b =>
                {
                    b.HasOne("Votify.Domain.EventFolder.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Votify.Domain.ProjectFolder.Project", b =>
                {
                    b.HasOne("Votify.Domain.CategoryFolder.Category", "Category")
                        .WithMany("Projects")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Votify.Domain.CategoryFolder.Category", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
